server:
  applicationConnectors:
    - type: http
      port: 9080
  adminConnectors:
    - type: http
      port: 9081

# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  # Logger-specific levels.
  loggers:
    com.bwarner.siteanalysis: DEBUG
    org.apache: ERROR
    org.springframework: ERROR
    httpclient: ERROR

  appenders:
    - type: console